trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
- stage: Test
  displayName: Test stage
  dependsOn: Build
  jobs:
  - job: Test
    displayName: Test
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
