trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-registry-chb-dev-1'
      repository: 'chabloom-billing-backend'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
