trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'chbpayments'
    repository: 'payments-backend-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
